# Pandas入门

In [2]:
import pandas as pd

## Series

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -1, 3], index = ['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -1
c    3
dtype: int64

In [9]:
obj2['a']

-1

In [10]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [11]:
obj2 * 2

d     8
b    14
a    -2
c     6
dtype: int64

In [12]:
import numpy as np

In [13]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.367879
c      20.085537
dtype: float64

In [14]:
'b' in obj2

True

In [15]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [16]:
obj3 = pd.Series(sdata)

In [17]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [18]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index = states)

In [19]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [22]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [26]:
obj4.name = 'population'

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [28]:
obj4.index.name = 'state'

In [29]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [30]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [31]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [32]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

## DateFrame

In [38]:
data = {
    'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
    'year': [2000, 2001, 22002, 2001, 2002, 2003],
    'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}
frame = pd.DataFrame(data)

In [39]:
frame

state   year  pop
0    Ohio   2000  1.5
1    Ohio   2001  1.7
2    Ohio  22002  3.6
3  Nevada   2001  2.4
4  Nevada   2002  2.9
5  Nevada   2003  3.2

In [40]:
frame.head()

state   year  pop
0    Ohio   2000  1.5
1    Ohio   2001  1.7
2    Ohio  22002  3.6
3  Nevada   2001  2.4
4  Nevada   2002  2.9

In [43]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0   2000    Ohio  1.5
1   2001    Ohio  1.7
2  22002    Ohio  3.6
3   2001  Nevada  2.4
4   2002  Nevada  2.9
5   2003  Nevada  3.2

In [44]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])

In [45]:
frame2

year   state  pop debt
one     2000    Ohio  1.5  NaN
two     2001    Ohio  1.7  NaN
three  22002    Ohio  3.6  NaN
four    2001  Nevada  2.4  NaN
five    2002  Nevada  2.9  NaN
six     2003  Nevada  3.2  NaN

In [46]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [22002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [47]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [48]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [50]:
frame2['year']

one       2000
two       2001
three    22002
four      2001
five      2002
six       2003
Name: year, dtype: int64

In [51]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [52]:
frame2.year

one       2000
two       2001
three    22002
four      2001
five      2002
six       2003
Name: year, dtype: int64

In [53]:
frame2.loc['three']

year     22002
state     Ohio
pop        3.6
debt       NaN
Name: three, dtype: object

In [54]:
frame2['debt'] = 16.5

In [55]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5  16.5
two     2001    Ohio  1.7  16.5
three  22002    Ohio  3.6  16.5
four    2001  Nevada  2.4  16.5
five    2002  Nevada  2.9  16.5
six     2003  Nevada  3.2  16.5

In [56]:
frame2['debt'] = np.arange(6)

In [57]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5     0
two     2001    Ohio  1.7     1
three  22002    Ohio  3.6     2
four    2001  Nevada  2.4     3
five    2002  Nevada  2.9     4
six     2003  Nevada  3.2     5

In [58]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [59]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [60]:
frame2['debt'] = val

In [62]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three  22002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
six     2003  Nevada  3.2   NaN

In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [65]:
frame2['eastern'] = frame.state = 'Ohio'

In [66]:
frame2

year   state  pop  debt eastern
one     2000    Ohio  1.5   NaN    Ohio
two     2001    Ohio  1.7  -1.2    Ohio
three  22002    Ohio  3.6   NaN    Ohio
four    2001  Nevada  2.4  -1.5    Ohio
five    2002  Nevada  2.9  -1.7    Ohio
six     2003  Nevada  3.2   NaN    Ohio

In [67]:
del frame2['eastern']

In [68]:
frame2

year   state  pop  debt
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three  22002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
six     2003  Nevada  3.2   NaN

In [70]:
pop = {
    'Nevda': { 2001: 2.4, 2002: 2.9 },
    'Ohio': { 2000: 1.5, 2001: 1.7, 2002: 3.6 }
}

In [71]:
frame3 = pd.DataFrame(pop)

In [72]:
frame3

Nevda  Ohio
2001    2.4   1.7
2002    2.9   3.6
2000    NaN   1.5

In [73]:
frame3.T

2001  2002  2000
Nevda   2.4   2.9   NaN
Ohio    1.7   3.6   1.5

In [74]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevda  Ohio
2001    2.4   1.7
2002    2.9   3.6
2003    NaN   NaN

In [76]:
pdata = {
    'Ohio': frame3['Ohio'][:-1],
    'Nevada': frame3['Nevda'][:2]
}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [77]:
frame2.index.name = 'year'; frame3.columns.name = 'state'

In [78]:
frame2

year   state  pop  debt
year                           
one     2000    Ohio  1.5   NaN
two     2001    Ohio  1.7  -1.2
three  22002    Ohio  3.6   NaN
four    2001  Nevada  2.4  -1.5
five    2002  Nevada  2.9  -1.7
six     2003  Nevada  3.2   NaN

In [79]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

### 索引对象

In [81]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index=  obj.index

In [82]:
index

Index(['a', 'b', 'c'], dtype='object')

In [83]:
index[1:]

Index(['b', 'c'], dtype='object')

In [84]:
labels = pd.Index(np.arange(3))

In [85]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [86]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [87]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [88]:
frame3

state  Nevda  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [90]:
frame3.columns

Index(['Nevda', 'Ohio'], dtype='object', name='state')

In [91]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [92]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [93]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [94]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'] )