In [13]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [4]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [6]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [7]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [8]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [14]:
frame = pd.DataFrame(np.arange(9).reshape(3, 3),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])

In [15]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [16]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [17]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [18]:
frame.reindex(columns=['Texas', 'Utah', 'California'])

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [22]:
states = ['Texas', 'Utah', 'California']

In [23]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [25]:
obj = pd.Series(np.arange(5.), index=['a', 'b','c', 'd', 'e'])

In [26]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [27]:
new_obj = obj.drop('c')

In [28]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [29]:
new_obj = new_obj.drop('b')

In [30]:
new_obj

a    0.0
d    3.0
e    4.0
dtype: float64

In [31]:
new_obj

a    0.0
d    3.0
e    4.0
dtype: float64

In [32]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [33]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [34]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [35]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [36]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [37]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [38]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [40]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [41]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [42]:
obj['b']

1.0

In [43]:
obj[1]

1.0

In [44]:
obj[['a', 'b']]

a    0.0
b    1.0
dtype: float64

In [45]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [46]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [48]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [49]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [50]:
obj['b':'c']=5

In [51]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [52]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [53]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [54]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [55]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [56]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [60]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [61]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [62]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [63]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int64

In [66]:
ser = pd.Series(np.arange(3.))

In [67]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [69]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [70]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [71]:
ser2[-1]

2.0

In [72]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [73]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
              index=['a', 'c', 'e', 'f', 'g'])

In [74]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [76]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                                        index=['Ohio', 'Texas', 'Colorado'])

In [78]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                                         index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [82]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [83]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [84]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [85]:
df1 = pd.DataFrame({'A': [1, 2]})

In [86]:
df2 = pd.DataFrame({'B': [3, 4]})

In [87]:
df1

A
0  1
1  2

In [88]:
df2

B
0  3
1  4

In [89]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [90]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))

In [91]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [92]:
df1 

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [93]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [94]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [95]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [96]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [97]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [98]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [99]:
arr = np.arange(12.).reshape((3, 4))

In [100]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

## DataFrame和Series之间的操作

In [101]:
arr = np.arange(12.).reshape((3, 4))

In [102]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [103]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [104]:
arr[0]

array([0., 1., 2., 3.])

In [105]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [108]:
series = frame.iloc[0]

In [109]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [110]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [111]:
series3 = frame['d']

In [112]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [113]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0