# 2 预备知识

## 2.2 数据操作

In [3]:
from mxnet import nd

In [4]:
x = nd.arange(12)

In [5]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [6]:
x.shape

(12,)

In [7]:
x.size

12

In [8]:
x = x.reshape(3, 4)

In [9]:
x


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [10]:
nd.zeros(2, 3, 4)

TypeError: Cannot interpret '4' as a data type

In [13]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [14]:
nd.ones((3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [17]:
Y = nd.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [18]:
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [19]:
nd.random.normal(0, 1, shape=(3, 4))


[[ 2.2122064   0.7740038   1.0434403   1.1839255 ]
 [ 1.8917114  -1.2347414  -1.771029   -0.45138445]
 [ 0.57938355 -1.856082   -1.9768796  -0.20801921]]
<NDArray 3x4 @cpu(0)>

In [20]:
X

NameError: name 'X' is not defined

In [22]:
x = 

SyntaxError: invalid syntax (<ipython-input-22-0f44b287cd63>, line 1)

In [23]:
x = nd.arange(12)

In [24]:
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [25]:
X = x.reshape(3, 4)

In [26]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [27]:
Y


[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [28]:
X + Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [29]:
X * Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [30]:
X / Y


[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [31]:
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [32]:
nd.dot(X, Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [33]:
nd.concat(X, Y, dim=0), nd.concat(X, Y, dim = 1)

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>,
 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

In [34]:
X == Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

In [35]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [36]:
X.norm().asscalar()

22.494442

In [37]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

In [38]:
X.sum().asscalar()

66.0

In [39]:
nd.exp(Y)


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

In [40]:
nd.sum(X)


[66.]
<NDArray 1 @cpu(0)>

In [41]:
nd.norm(X)


[22.494442]
<NDArray 1 @cpu(0)>

In [42]:
A = nd.arane(3).reshape(3, 1)

AttributeError: module 'mxnet.ndarray' has no attribute 'arane'

In [43]:
A = nd.arrang(3).reshape((3, 1))

AttributeError: module 'mxnet.ndarray' has no attribute 'arrang'

In [44]:
A = nd.arange(3).reshape((3, 1))

In [45]:
B = nd.arange(2).reshape((1, 2))

In [46]:
A


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)>

In [47]:
B


[[0. 1.]]
<NDArray 1x2 @cpu(0)>

In [48]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [49]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

In [50]:
X[1, 2] = 9

In [51]:
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [52]:
X[1:2, :] = 12

In [53]:
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [55]:
before = id(Y)

In [56]:
Y = Y + X

In [65]:
id(Y) == before

False

In [67]:
X[:] = X + Y

In [68]:
X


[[ 4.  5. 14. 15.]
 [38. 40. 42. 44.]
 [32. 33. 34. 35.]]
<NDArray 3x4 @cpu(0)>

In [69]:
X += Y

In [70]:
X


[[ 6.  7. 20. 21.]
 [51. 54. 57. 60.]
 [44. 45. 46. 47.]]
<NDArray 3x4 @cpu(0)>

In [72]:
import numpy as np

In [73]:
P = np.ones((2, 3))

In [74]:
P

array([[1., 1., 1.],
       [1., 1., 1.]])

In [75]:
D = nd.array(P)

In [76]:
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [77]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [78]:
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [79]:
X = D.asnumpy()

In [80]:
X

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [81]:
X < Y

TypeError: type <class 'numpy.ndarray'> not supported

In [82]:
X

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [83]:
nd.array(X)


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [84]:
X

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [85]:
X = nd.array(X)

In [86]:
X


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [87]:
X


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [88]:
Y


[[ 2.  2.  6.  6.]
 [13. 14. 15. 16.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [89]:
X < Y

MXNetError: Traceback (most recent call last):
  File "src/operator/numpy/linalg/./../../tensor/elemwise_binary_broadcast_op.h", line 68
MXNetError: Check failed: l == 1 || r == 1: operands could not be broadcast together with shapes [2,3] [3,4]

In [90]:
X


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [91]:
Y


[[ 2.  2.  6.  6.]
 [13. 14. 15. 16.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

## 2.3 自动求梯度

In [92]:
from mxnet import autograd, nd

In [93]:
x = nd.arange(4).reshape((4, 1))

In [94]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [95]:
x.attach_grad()

In [98]:
with autograd.record():
    y = 2 * nd.dot(x.T, x)

In [100]:
y.backward()

In [101]:
y


[[28.]]
<NDArray 1x1 @cpu(0)>

In [102]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [103]:
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [105]:
with autograd.record():
    2 * nd.dot(x.T, x)

In [106]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [109]:
with autograd.record():
    y * nd.dot(x.T, x)

In [110]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [112]:
print(autograd.is_training())
with autograd.record():
    print(autograd.is_training())

False
True


In [113]:
def f(a):
    b = a * 2
    while b.norm().asscalar() < 1000:
        b = b * 2
    if b.sum().asscalar() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = nd.random.normal(shape=1)
a.attach_grad()
with autograd.record():
    c = f(a)
c.backward()

In [114]:
a.grad


[4096.]
<NDArray 1 @cpu(0)>

In [115]:
print(dir(nd.random))

['NDArray', '_Null', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_internal', '_random_helper', 'current_context', 'exponential', 'exponential_like', 'gamma', 'gamma_like', 'generalized_negative_binomial', 'generalized_negative_binomial_like', 'multinomial', 'negative_binomial', 'negative_binomial_like', 'normal', 'normal_like', 'numeric_types', 'poisson', 'poisson_like', 'randint', 'randn', 'shuffle', 'uniform', 'uniform_like']


In [116]:
help(nd.ones_like)

Help on function ones_like:

ones_like(data=None, out=None, name=None, **kwargs)
    Return an array of ones with the same shape and type
    as the input array.
    
    Examples::
    
      x = [[ 0.,  0.,  0.],
           [ 0.,  0.,  0.]]
    
      ones_like(x) = [[ 1.,  1.,  1.],
                      [ 1.,  1.,  1.]]
    
    
    
    Parameters
    ----------
    data : NDArray
        The input
    
    out : NDArray, optional
        The output NDArray to hold the result.
    
    Returns
    -------
    out : NDArray or list of NDArrays
        The output of this function.



In [117]:
nd.ones_like?