In [1]:
import numpy as np 

def sigmoid(x):
    """
    Compute the sigmoid of x

    Arguments:
    x -- A scalar or numpy array of any size

    Return:
    s -- sigmoid(x)
    """
    s = 1 / (1 + np.exp(-x))
    
    return s

In [2]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [3]:
def sigmoid_derivative(x):
    s = sigmoid(x)
    ds = sigmoid(x) * (1 - sigmoid(x))
    return ds

In [4]:
x = np.array([1, 2, 3])
sigmoid_derivative(x)

array([0.19661193, 0.10499359, 0.04517666])

In [8]:
def image2vector(image):
    v = image.reshape((v.shape[0] * v.shape[1] * v.shape[2], 1))
    return v

In [11]:
def normalize_rows(x):
    x_norm = np.linalg.norm(x, axis=1, keepdims=True)
    x = x / x_norm
    return x

In [12]:
x = np.array([
    [0, 3, 4],
    [1, 6, 4]
])
normalize_rows(x)

array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])

In [14]:
def softmax(x):
    x_exp = np.exp(x)
    x_sum = np.sum(x_exp, axis=1, keepdims=True)
    s = np.exp(x) / x_sum
    return s

In [15]:
def L1(yhat, y):
    los = np.sum(np.abs(y - yhat))
    return loss

In [16]:
def L2(yhat, y):
    d = y - yhat
    loss = np.sum(np.dot(d, d))
    return loss