In [2]:
import numpy as np

In [7]:
b = np.random.randn(1, 1, 1)
b

array([[[-0.4981391]]])

In [8]:
float(b)

-0.49813909689170577

In [10]:
np.random.seed(1)
A_prev = np.random.randn(2, 5, 7, 4)

In [12]:
A_prev.shape

(2, 5, 7, 4)

In [13]:
W = np.random.randn(3, 3, 4, 8)

In [18]:
w = W[:,:,:,0]

In [20]:
w[0]

array([[-0.78191168, -1.11647002,  0.417302  , -0.27909772],
       [ 1.3887794 , -0.13597733, -0.23794194, -2.03720123],
       [-0.10999149, -0.19505734, -0.55749472,  0.58464661]])

In [17]:
W

array([[[[-0.78191168, -0.43750898,  0.09542509,  0.92145007,
           0.0607502 ,  0.21112476,  0.01652757,  0.17718772],
         [-1.11647002,  0.0809271 , -0.18657899, -0.05682448,
           0.49233656, -0.68067814, -0.08450803, -0.29736188],
         [ 0.417302  ,  0.78477065, -0.95542526,  0.58591043,
           2.06578332, -1.47115693, -0.8301719 , -0.8805776 ],
         [-0.27909772,  1.62284909,  0.01335268, -0.6946936 ,
           0.6218035 , -0.59980453,  1.12341216,  0.30526704]],

        [[ 1.3887794 , -0.66134424,  3.03085711,  0.82458463,
           0.65458015, -0.05118845, -0.72559712, -0.86776868],
         [-0.13597733, -0.79726979,  0.28267571, -0.82609743,
           0.6210827 ,  0.9561217 , -0.70584051,  1.19268607],
         [-0.23794194,  1.15528789,  0.43816635,  1.12232832,
          -0.9970198 , -0.10679399,  1.45142926, -0.61803685],
         [-2.03720123, -1.94258918, -2.50644065, -2.11416392,
          -0.41163916,  1.27852808, -0.44222928,  0.32352735]

In [23]:
b = np.random.randn(1, 1, 1, 8)

In [24]:
b

array([[[[ 1.16143998, -0.02752939,  1.74643509, -0.77507029,
           0.14164054, -2.51630386, -0.59566788, -0.30912132]]]])

In [26]:
b2 = np.random.randn(1, 1, 1)
b2

array([[[1.71066184]]])

In [27]:
b[0]

array([[[ 1.16143998, -0.02752939,  1.74643509, -0.77507029,
          0.14164054, -2.51630386, -0.59566788, -0.30912132]]])

In [29]:
b[:,:,:,0]

array([[[1.16143998]]])

In [30]:
b3 = b[:,:,:,2]

In [31]:
b2 + b3

array([[[3.45709693]]])