In [1]:
import numpy

In [2]:
numpy.__version__

'1.20.1'

In [3]:
import numpy as np

In [4]:
np?

In [5]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
np.array([1, 4, 2, 5, 3], dtype='float32')

array([1., 4., 2., 5., 3.], dtype=float32)

In [8]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.random.normal(0, 1, (3, 3))

array([[ 1.4922991 , -0.66037437,  2.50579237],
       [ 0.55480589,  1.46750081, -0.82927658],
       [-0.64200612,  0.81447238,  1.21114101]])

In [20]:
np.random.random((3, 3))

array([[0.17828859, 0.50247129, 0.74172087],
       [0.81724554, 0.33858284, 0.21541354],
       [0.05272488, 0.10477665, 0.95259889]])

In [21]:
np.random.randint(0, 10, (3, 3))

array([[2, 8, 6],
       [0, 2, 5],
       [8, 6, 9]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.empty(3)

array([1., 1., 1.])

## 数组基础

In [25]:
import numpy as np

In [26]:
np.random.seed(0)

In [29]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [32]:
x3.ndim

3

In [33]:
x3.shape

(3, 4, 5)

In [30]:
x3.size

60

In [31]:
print("dtype:", x3.dtype)

dtype: int64


In [34]:
x1[0]

8

In [35]:
x1[4]

7

In [36]:
x1[-1]

7

In [37]:
x1[-2]

7

In [38]:
x2[0, 0]

8

In [39]:
x2[2, -1]

0

In [40]:
x2[0, 0] = 12

In [43]:
x = np.arange(10)

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x[:5]

array([0, 1, 2, 3, 4])

In [46]:
x[5:]

array([5, 6, 7, 8, 9])

In [47]:
x[4:7]

array([4, 5, 6])

In [48]:
x[::2]

array([0, 2, 4, 6, 8])

In [49]:
x[1::2]

array([1, 3, 5, 7, 9])

In [50]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [51]:
x[5::-2]

array([5, 3, 1])

In [52]:
x2

array([[12,  1,  5,  9],
       [ 8,  9,  4,  3],
       [ 0,  3,  5,  0]])

In [53]:
x2[:2, :3]

array([[12,  1,  5],
       [ 8,  9,  4]])

In [54]:
x2[::-1, ::-1]

array([[ 0,  5,  3,  0],
       [ 3,  4,  9,  8],
       [ 9,  5,  1, 12]])

In [55]:
x2[:, 0]

array([12,  8,  0])

In [56]:
x2[0, :]

array([12,  1,  5,  9])

In [57]:
x2[0]

array([12,  1,  5,  9])

## 切片是视图

In [58]:
x2

array([[12,  1,  5,  9],
       [ 8,  9,  4,  3],
       [ 0,  3,  5,  0]])

In [59]:
x2_sub = x2[:2, :2]

In [60]:
x2_sub

array([[12,  1],
       [ 8,  9]])

In [61]:
x2_sub[0, 0] = 99

In [62]:
x2_sub

array([[99,  1],
       [ 8,  9]])

In [63]:
x2

array([[99,  1,  5,  9],
       [ 8,  9,  4,  3],
       [ 0,  3,  5,  0]])

In [64]:
x2_copy = x2[:2, :2].copy()

## 数组变形

In [65]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [66]:
x = np.array([1, 2, 3])

In [67]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [68]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [69]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [70]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## 拼接和分裂

In [75]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [76]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [77]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [79]:
x = np.array([1, 2, 3])
grid =  np.array([[9, 8, 7], [6, 5, 4]])

In [80]:
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [81]:
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [83]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [84]:
grid = np.arange(16).reshape((4, 4))

In [85]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
upper, lower = np.vsplit(grid, [2])

In [87]:
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


## 通用计算 

In [88]:
values = np.random.randint(1, 10, size=5)

In [89]:
1.0 / values

array([0.16666667, 0.25      , 1.        , 0.16666667, 1.        ])

In [90]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.5       , 0.33333333, 0.2       , 0.33333333, 1.        ])

In [91]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.16 s ± 31.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [92]:
%timeit (1.0 / big_array)

1.17 ms ± 3.71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [93]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [94]:
x = np.arange(9).reshape((3, 3))

In [95]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [96]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

## 通用函数

In [97]:
x = np.arange(4)

In [98]:
x + 5


array([5, 6, 7, 8])

In [99]:
x

array([0, 1, 2, 3])

In [100]:
x - 5

array([-5, -4, -3, -2])

In [101]:
x * 2

array([0, 2, 4, 6])

In [102]:
x  / 2

array([0. , 0.5, 1. , 1.5])

In [103]:
x // 2

array([0, 0, 1, 1])

In [104]:
-x

array([ 0, -1, -2, -3])

In [105]:
x ** 2

array([0, 1, 4, 9])

In [106]:
x % 2

array([0, 1, 0, 1])

In [107]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [108]:
np.add(x, 2)

array([2, 3, 4, 5])

In [109]:
x = np.array([-2, -1, 0, ])
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [111]:
x = np.array([3 - 4j, 4 - 3j, 0 + 1j])

In [112]:
np.abs(x)

array([5., 5., 1.])

In [113]:
theta = np.linspace(0, np.pi, 3)

In [114]:
theta

array([0.        , 1.57079633, 3.14159265])

In [115]:
np.sin(theta)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [116]:
np.cos(theta)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [117]:
np.tan(theta)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

In [118]:
x = [-1, 0, 1]

In [119]:
np.arcsin(x)

array([-1.57079633,  0.        ,  1.57079633])

In [120]:
np.arccos(x)

array([3.14159265, 1.57079633, 0.        ])

In [121]:
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [122]:
x = [1, 2, 3]

In [123]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [124]:
np.exp2(x)

array([2., 4., 8.])

In [125]:
np.power(3, x)

array([ 3,  9, 27])

In [126]:
x = [1, 2, 3, 4]

In [127]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [128]:
np.log2(x)

array([0.       , 1.       , 1.5849625, 2.       ])

In [129]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999])

In [136]:
np.expm1(x)   # x 很小时使用

array([ 1.71828183,  6.3890561 , 19.08553692, 53.59815003])

In [137]:
np.log1p(x)  # x 很小时使用

array([0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [139]:
from scipy import special

In [140]:
x = [1, 5, 10]

In [141]:
special.gamma(x)

array([1.0000e+00, 2.4000e+01, 3.6288e+05])

In [142]:
special.gammaln(x)

array([ 0.        ,  3.17805383, 12.80182748])

In [143]:
special.beta(x, 2)

array([0.5       , 0.03333333, 0.00909091])

In [147]:
x = [0, 0.3, 0.7, 1.0]

In [148]:
special.erf(x)

array([0.        , 0.32862676, 0.67780119, 0.84270079])

In [149]:
special.erfc(x)

array([1.        , 0.67137324, 0.32219881, 0.15729921])

In [150]:
special.erfinv(x)

array([0.        , 0.27246271, 0.73286908,        inf])

## 高极通用函数的特性

In [151]:
x = np.array(5)

In [152]:
y = np.empty(5)

In [153]:
np.multiply(x, 10, out = y)

array([50., 50., 50., 50., 50.])

In [154]:
y

array([50., 50., 50., 50., 50.])

In [155]:
y = np.zeros(10)

In [156]:
np.power(2, x, out=y[::2])

array([32., 32., 32., 32., 32.])

In [157]:
y

array([32.,  0., 32.,  0., 32.,  0., 32.,  0., 32.,  0.])

In [158]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [159]:
np.multiply.reduce(x)

120

In [160]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [162]:
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])