In [1]:
import pandas as pd
import numpy as np

In [2]:
def make_df(cols, ind):
    """一个简单的DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data, ind)

make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [3]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x = [[1, 2], [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [5]:
x = [[1, 2], [3, 4]]
np.concatenate([x, x], axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [6]:
ser1= pd.Series(['A', 'B', 'C'], index=[1, 2, 3])

In [7]:
ser1

1    A
2    B
3    C
dtype: object

In [8]:
ser2 = pd.Series(['D', 'E', 'F'], index=[4, 5, 6])

In [10]:
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [11]:
df1 = make_df('AB', [1, 2])

In [12]:
df2 = make_df('AB', [3, 4])

In [13]:
df1, df2

(    A   B
 1  A1  B1
 2  A2  B2,
     A   B
 3  A3  B3
 4  A4  B4)

In [14]:
pd.concat([df1, df2])

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [15]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])

In [16]:
df3

A   B
0  A0  B0
1  A1  B1

In [17]:
df4

C   D
0  C0  D0
1  C1  D1

In [19]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [22]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index

In [23]:
pd.concat([x, y])

A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3

In [24]:
pd.concat([x, y], ignore_index=True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [25]:
pd.concat([x, y], keys=['x', 'y'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [26]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])

In [27]:
pd.concat([df5, df6])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [28]:
pd.concat([df5, df6], join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [30]:
pd.concat([df5, df6], join_axes=[df5.columns])

TypeError: concat() got an unexpected keyword argument 'join_axes'

In [31]:
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4