In [1]:
import pandas as pd
import numpy as np

In [2]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int64

In [3]:
rng.randint(0, 10, 4)

array([6, 9, 2, 6])

In [4]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                 columns=['A', 'B', 'C', 'D'])

In [5]:
df

A  B  C  D
0  7  4  3  7
1  7  2  5  4
2  1  7  5  1

In [6]:
rng.randint(0, 10, (3, 4))

array([[4, 0, 9, 5],
       [8, 0, 9, 2],
       [6, 3, 8, 2]])

In [7]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [8]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -0.707107  1.224647e-16  0.707107 -7.071068e-01
1 -0.707107  1.000000e+00 -0.707107  1.224647e-16
2  0.707107 -7.071068e-01 -0.707107  7.071068e-01

In [10]:
area = pd.Series({
    'Alaska': 1723337,
    'Texas': 695662,
    'California': 423967,
}, name='area')

In [11]:
population = pd.Series({
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127
}, name='population')

In [12]:
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [13]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [14]:
area.index | population.index

<ipython-input-14-ff558a211efb>:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  area.index | population.index


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [15]:
area.index.union(population.index)

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [17]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [18]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [19]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                columns=list('AB'))

In [20]:
A

A   B
0  4  18
1  6   8

In [22]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))

In [23]:
fill = A.stack().mean()

In [24]:
A.stack()

0  A     4
   B    18
1  A     6
   B     8
dtype: int64

In [25]:
fill

9.0

In [26]:
A.add(B, fill_value=fill)

A     B     C
0   5.0  24.0  12.0
1   7.0  16.0  18.0
2  18.0  17.0  13.0

In [27]:
A = rng.randint(10, size=(3, 4))

In [28]:
A

array([[1, 3, 6, 7],
       [2, 0, 3, 1],
       [7, 3, 1, 5]])

In [29]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 1, -3, -3, -6],
       [ 6,  0, -5, -2]])

In [30]:
df = pd.DataFrame(A, columns=list('QRST'))

In [31]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  1 -3 -3 -6
2  6  0 -5 -2

In [32]:
df.iloc[0]

Q    1
R    3
S    6
T    7
Name: 0, dtype: int64

In [34]:
df

Q  R  S  T
0  1  3  6  7
1  2  0  3  1
2  7  3  1  5

In [35]:
df['Q']

0    1
1    2
2    7
Name: Q, dtype: int64

In [37]:
df.loc[0]

Q    1
R    3
S    6
T    7
Name: 0, dtype: int64

In [40]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -2  0  3  4
1  2  0  3  1
2  4  0 -2  2

In [41]:
halfrow = df.iloc[0, ::2]

In [42]:
import numpy as np
import pandas as pd

In [43]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [44]:
for dtype in ['object', 'int']:
    print("dtype =", dtype)
    %timeit np.arange(1e6, dtype=dtype).sum()
    print()

dtype = object
38.1 ms ± 913 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

dtype = int
826 µs ± 32.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)



In [49]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [50]:
1 + np.nan

nan

In [52]:
vals1

array([1, None, 3, 4], dtype=object)

In [53]:
vals2 = np.array([1, np.nan, 3, 4])

In [54]:
vals2.dtype

dtype('float64')

In [55]:
vals2.sum()

nan

In [56]:
vals2.min()

nan

In [57]:
vals2.max()

nan

In [58]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [59]:
x = pd.Series(range(2), dtype=int)

In [60]:
x

0    0
1    1
dtype: int64

In [61]:
data = pd.Series([1, np.nan, 'hello', None])

In [62]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [63]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [64]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [65]:
data.dropna()

0        1
2    hello
dtype: object

In [66]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [67]:
data.dropna()

0        1
2    hello
dtype: object

In [68]:
df.dropna(axis='columns')

Q  R  S  T
0  1  3  6  7
1  2  0  3  1
2  7  3  1  5

In [69]:
df

Q  R  S  T
0  1  3  6  7
1  2  0  3  1
2  7  3  1  5

In [70]:
df = pd.DataFrame([
    [1, np.nan, 2],
    [2, 3, 5],
    [np.nan, 4, 6]
])


In [71]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [72]:
df.dropna(axis='columns')

2
0  2
1  5
2  6

In [74]:
df.dropna(axis='columns', thresh=3)

2
0  2
1  5
2  6

In [76]:
data = pd.Series([1, np.nan, 2, None, 3],
                index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [77]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [78]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [79]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [80]:
df.fillna(method='ffill', axis=1)

0    1    2
0  1.0  1.0  2.0
1  2.0  3.0  5.0
2  NaN  4.0  6.0

In [81]:
import pandas as pd
import numpy as np

In [82]:
index = [
    ('California', 2000),
    ('California', 2010),
    ('New York', 2000),
    ('New York', 2010),
    ('Texas', 2000),
    ('Texas', 2010)
]

populations = [
    33871648, 37253956,
    18976457, 19378102,
    20851820, 25145561
]
pop = pd.Series(populations, index=index)

In [83]:
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [84]:
index = pd.MultiIndex.from_tuples(index)

In [85]:
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [91]:
pop = pop.reindex(index)

In [92]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [93]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [94]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [95]:
pop_df = pop.unstack()

In [96]:
pop_df

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [97]:
pop_df.stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [98]:
pop_df = pd.DataFrame({
    'total': pop,
    'under18': [
        9267089, 9284094,
        4687373, 4318033,
        5906301, 6879014
    ]
})

In [99]:
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687373
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [100]:
f_u18 = pop_df['under18'] / pop_df['total']

In [101]:
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [102]:
pop_df['under18']

California  2000    9267089
            2010    9284094
New York    2000    4687373
            2010    4318033
Texas       2000    5906301
            2010    6879014
Name: under18, dtype: int64

In [103]:
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [104]:
df = pd.DataFrame(np.random.rand(4, 2),
                 index =[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                 columns=['data1', 'data2'])

In [105]:
df

data1     data2
a 1  0.971468  0.651524
  2  0.618199  0.923290
b 1  0.395474  0.870705
  2  0.887550  0.027393

In [106]:
data = {
    ('California', 2000): 33871648,
    ('California', 2010): 37253956,
    ('Texas', 2000): 20851820,
    ('Texas', 2010): 25145561,
    ('New York', 2000): 18976457,
    ('New York', 2010): 19378102
}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

In [108]:
pd.MultiIndex.from_arrays([
    ['a', 'a', 'b', 'b'],
    [1, 2, 1, 2]
])


MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [109]:
pd.MultiIndex.from_tuples([
    ('a', 1),
    ('a', 2),
    ('b', 1),
    ('b', 2)
])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [110]:
pd.MultiIndex.from_product([
    ['a', 'b'],
    [1, 2]
])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [112]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
             labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

TypeError: __new__() got an unexpected keyword argument 'labels'

In [113]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [114]:
pop.index.names = ['state', 'year']

In [115]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [116]:
index = pd.MultiIndex.from_product(
    [[2013, 2014], [1, 2]],
    names=['year', 'visit']
)

In [117]:
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [126]:
columns = pd.MultiIndex.from_product([
    ['Bob', 'Guido', 'Sue'],
    ['HR', 'Temp']
], names=['subject', 'type'])

In [119]:
data = np.round(np.random.randn(4, 6), 1)

In [120]:
data

array([[-0.4,  0.5, -0. ,  0.9,  0.6,  1.5],
       [-0.3,  1.4, -1. ,  0.7, -0.2, -1.6],
       [ 0.5, -0.5, -1.8,  1. , -0.2, -0.1],
       [ 1. ,  0.2, -0.4,  0.5,  2.9,  0.4]])

In [121]:
np.random.randn(4, 6)

array([[ 0.31353825, -0.87864766, -1.20270744,  2.14391059, -0.97105143,
        -0.07318116],
       [-0.18954986,  0.3322068 , -0.17228703, -1.97895941,  0.37495951,
         1.01961206],
       [-1.90867837, -1.0607671 ,  0.25080386,  0.7151809 ,  0.33520024,
        -0.53733965],
       [ 0.18889344, -0.43315035, -0.87885092, -0.31093986, -0.17140486,
        -2.55856208]])

In [122]:
data[:, ::2] *= 2

In [123]:
data

array([[-0.8,  0.5, -0. ,  0.9,  1.2,  1.5],
       [-0.6,  1.4, -2. ,  0.7, -0.4, -1.6],
       [ 1. , -0.5, -3.6,  1. , -0.4, -0.1],
       [ 2. ,  0.2, -0.8,  0.5,  5.8,  0.4]])

In [124]:
data += 37

In [127]:
health_data = pd.DataFrame(data, index=index, columns=columns)

In [128]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.2  37.5  37.0  37.9  38.2  38.5
     2      36.4  38.4  35.0  37.7  36.6  35.4
2014 1      38.0  36.5  33.4  38.0  36.6  36.9
     2      39.0  37.2  36.2  37.5  42.8  37.4

In [129]:
pop


state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [130]:
pop['California', 2000]

33871648

In [131]:
pop['California']

year
2000    33871648
2010    37253956
dtype: int64

In [132]:
pop[:, 2000]

state
California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [133]:
pop[pop > 22000000]

state       year
California  2000    33871648
            2010    37253956
Texas       2010    25145561
dtype: int64

In [134]:
pop[['California', 'Texas']]

state       year
California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
dtype: int64

In [135]:
health_data['Guido', 'HR']

year  visit
2013  1        37.0
      2        35.0
2014  1        33.4
      2        36.2
Name: (Guido, HR), dtype: float64

In [137]:
health_data.iloc[:2, :2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      36.2  37.5
     2      36.4  38.4

In [138]:
health_data.loc[:, ('Bob', 'HR')]

year  visit
2013  1        36.2
      2        36.4
2014  1        38.0
      2        39.0
Name: (Bob, HR), dtype: float64

In [142]:
health_data.loc[(:, 1), (:, 'HR')]

SyntaxError: invalid syntax (<ipython-input-142-fb34fa30ac09>, line 1)

In [143]:
idx = pd.IndexSlice
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      36.2  37.0  38.2
2014 1      38.0  33.4  36.6

In [148]:
index = pd.MultiIndex.from_product([
    ['a', 'c', 'b'], [1, 2]
])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.216502
      2      0.536693
c     1      0.655786
      2      0.457464
b     1      0.402476
      2      0.207765
dtype: float64

In [149]:
try:
    data['a': 'b']
except KeyError as e:
    print(type(e))
    print(e)


<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [150]:
data = data.sort_index()


In [151]:
data

char  int
a     1      0.216502
      2      0.536693
b     1      0.402476
      2      0.207765
c     1      0.655786
      2      0.457464
dtype: float64

In [152]:
data['a': 'b']

char  int
a     1      0.216502
      2      0.536693
b     1      0.402476
      2      0.207765
dtype: float64

In [153]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2000     33871648  18976457  20851820
2010     37253956  19378102  25145561

In [154]:
pop.unstack(level=1)

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [155]:
pop.unstack().stack()

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [156]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [157]:
pop_flat = pop.reset_index(name='population')

In [158]:
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [159]:
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [160]:
pop_flat.set_index(['state', 'year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [161]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      36.2  37.5  37.0  37.9  38.2  38.5
     2      36.4  38.4  35.0  37.7  36.6  35.4
2014 1      38.0  36.5  33.4  38.0  36.6  36.9
     2      39.0  37.2  36.2  37.5  42.8  37.4

In [162]:
data_mean = health_data.mean(level='year')

In [163]:
data_mean

subject   Bob        Guido          Sue       
type       HR   Temp    HR   Temp    HR   Temp
year                                          
2013     36.3  37.95  36.0  37.80  37.4  36.95
2014     38.5  36.85  34.8  37.75  39.7  37.15

In [164]:
data_mean.mean(axis=1, level='type')

type         HR       Temp
year                      
2013  36.566667  37.566667
2014  37.666667  37.250000